Repository UMC-CommonPlant/CommonPlant-iOS-refactoring, pull requests merged in 2023-08, with the labels that each got.

#19 Feat/#15 식물 검색탭 UI 구현
  CommonPlant/CommonPlant.xcodeproj/project.pbxproj
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/AirPurification.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/AirPurification.imageset/Property 1=공기정화.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/AirPurification.imageset/Property 1=공기정화@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/AirPurification.imageset/Property 1=공기정화@3x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Beginner.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Beginner.imageset/Property 1=초보집사.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Beginner.imageset/Property 1=초보집사@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Beginner.imageset/Property 1=초보집사@3x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Color Set/AirPurificationColor.colorset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Color Set/BeginnerColor.colorset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Color Set/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Color Set/InteriorColor.colorset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Color Set/OneRoomColor.colorset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Color Set/SunlightColor.colorset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Color Set/WaterPreferenceColor.colorset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Interior.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Interior.imageset/Property 1=인테리어.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Interior.imageset/Property 1=인테리어@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Interior.imageset/Property 1=인테리어@3x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/OneRoom.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/OneRoom.imageset/Property 1=원룸.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/OneRoom.imageset/Property 1=원룸@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/OneRoom.imageset/Property 1=원룸@3x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Sunlight.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Sunlight.imageset/Property 1=햇빛.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Sunlight.imageset/Property 1=햇빛@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/Sunlight.imageset/Property 1=햇빛@3x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/WateringPot.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/WateringPot.imageset/Property 1=물뿌리개.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/WateringPot.imageset/Property 1=물뿌리개@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/SearchPlant/WateringPot.imageset/Property 1=물뿌리개@3x.png
  CommonPlant/CommonPlant/Screen/Main/ViewController/MainMyPlaceCollectionViewCell.swift
  CommonPlant/CommonPlant/Screen/Main/ViewController/MainMyPlantCollectionViewCell.swift
  CommonPlant/CommonPlant/Screen/Main/ViewController/MainTabBarController.swift
  CommonPlant/CommonPlant/Screen/Main/ViewController/MainViewController.swift
  CommonPlant/CommonPlant/Screen/PlantSearch/Model/PoplularSearchModel.swift
  CommonPlant/CommonPlant/Screen/PlantSearch/Model/SearchResultModel.swift
  CommonPlant/CommonPlant/Screen/PlantSearch/ViewController/PlantSearchCollectionViewCell.swift
  CommonPlant/CommonPlant/Screen/PlantSearch/ViewController/PlantSearchViewController.swift
  CommonPlant/CommonPlant/Screen/PlantSearch/ViewController/PopularSearchCollectionViewCell.swift
  CommonPlant/CommonPlant/Screen/PlantSearch/ViewController/SearchResultTableViewCell.swift
  CommonPlant/CommonPlant/Screen/PlantSearch/ViewController/SearchResultViewController.swift
  CommonPlant/CommonPlant/Screen/PlantSearch/ViewModel/PlantSearchViewModel.swift
  CommonPlant/CommonPlant/Screen/PlantSearch/ViewModel/SearchResultViewModel.swift
Labels: ✨FEAT, 샬롯🧅, ☘️PlantInfo

#20 [Feat] 사진첩 사용 로직 분리
  CommonPlant/CommonPlant.xcodeproj/project.pbxproj
  CommonPlant/CommonPlant/Global/Extensions/UIViewController+Extension.swift
  CommonPlant/CommonPlant/Screen/Authentication/View/SignUpViewController.swift
  CommonPlant/CommonPlant/Screen/ImagePicker/View/ImagePickerCollectionViewCell.swift
  CommonPlant/CommonPlant/Screen/ImagePicker/View/ImagePickerViewController.swift
  CommonPlant/CommonPlant/Screen/ImagePicker/ViewModel/ImagePickerViewModel.swift
  CommonPlant/CommonPlant/Screen/MyPage/View/EditUserInfoViewController.swift
  CommonPlant/CommonPlant/Screen/MyPage/ViewModel/EditUserInfoViewModel.swift
Labels: ✨FEAT, 오즈🌈, ☘️Photo

#22 [Feat] My Plant View UI 구현
  CommonPlant/CommonPlant.xcodeproj/project.pbxproj
  CommonPlant/CommonPlant/Global/Extensions/UIView+Extension.swift
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Button/Menu.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Button/Menu.imageset/more.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Button/Menu.imageset/more@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Button/Menu.imageset/more@3x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Button/Next.imageset/Back.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Button/Next.imageset/Back@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Button/Next.imageset/Back@3x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Button/Next.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Humidity.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Humidity.imageset/Icon.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Humidity.imageset/Icon@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Humidity.imageset/Icon@3x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Place.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Place.imageset/material-symbols_add-home-outline-rounded.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Place.imageset/material-symbols_add-home-outline-rounded@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Place.imageset/material-symbols_add-home-outline-rounded@3x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Temperature.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Temperature.imageset/Icon.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Temperature.imageset/Icon@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/Temperature.imageset/Icon@3x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/WateringCan.imageset/Contents.json
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/WateringCan.imageset/Vector.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/WateringCan.imageset/Vector@2x.png
  CommonPlant/CommonPlant/Resource/Assets.xcassets/Icon/WateringCan.imageset/Vector@3x.png
  CommonPlant/CommonPlant/Screen/MyPlant/Model/MyPlantModel.swift
  CommonPlant/CommonPlant/Screen/MyPlant/View/MemoCollectionViewCell.swift
  CommonPlant/CommonPlant/Screen/MyPlant/View/MyPlantViewController.swift
  CommonPlant/CommonPlant/Screen/MyPlant/ViewModel/MyPlantViewModel.swift
Labels: ✨FEAT, 오즈🌈, ☘️MyPlant
